### ISSUE TITLE
Code crash

### ISSUE THREAD

**Issue by DanishMalhotra** [uvbakutan/lane-detection-raspberry-pi#1]
Hi m facing a issue with the code. while running the code it crashes automatically after 1 sec and throws a error ValueError: on entry to DLASCL parameter number 4 had an illegal value
m using numpy version 1.13.3 with python 2.7 and open cv 3.0.0

Any idea?

**Comment by rjuarez7** [comment]
I used OpenCV , not OpenCV 3.

**Comment by DanishMalhotra** [comment]
Hi thanks for ur quick reply

U mentioned in your read me document that u r using opencv version 3 only

**Comment by uvbakutan** [comment]
I have not tried to run the program with other versions of python, numpy or opencv. I would recommend to install all the same versions I used and start from there.

**Comment by DanishMalhotra** [comment]
Thanks I'll install the same.. And one more thing how u r reading the video input using pi camera or sample video

On Dec 3, 2017 9:34 PM, uvbakutan <notifications@github.com> wrote:

I have not tried to run the program with other versions of python, numpy or opencv. I would recommend to install all the same versions I used and start from there.

**Comment by uvbakutan** [comment]
I'm using "picamera" and the  camera.capture_continuous function. You can have a look at the bottom of lane-detect-pi.py. :)

**Comment by rjuarez7** [comment]
I use a webcam plugged on one usb port. I don't use the picamera.

**Comment by uvbakutan** [comment]
Maybe I misunderstood you question DanishMalhotra. I play the video on my PC screen and then use picamera to detected the lanes on the video.

**Comment by DanishMalhotra** [comment]
Ya that's what I wanted to know. I have to start that sample video which u have given only then that code will work. Any idea if I want to real time process that code. Like using camera module and going on a road.. What changes I have to make in that code if I have to run it real time

On Dec 4, 2017 2:04 AM, uvbakutan <notifications@github.com> wrote:

Maybe I misunderstood you question. I play the video on my PC screen and then use picamera to detected the lanes on the video.

**Comment by rjuarez7** [comment]
For complete line tracking , my example will not work, maybe you can check following link.

https://github.com/naokishibuya/car-finding-lane-lines

**Comment by uvbakutan** [comment]
Actually I built the code specifically to run on real time with 7fps (frames per second) on the raspberry pi.  The raspberry captures the video with the camera. I tested it with pointing the camera to my PC screen ( not raspberry pi). You should be able to test it with other videos or take it to the road without adding anything.

**Comment by DanishMalhotra** [comment]
Ok I'll try tonight.. Will install the same versions for which u have written code

On Dec 4, 2017 7:28 PM, uvbakutan <notifications@github.com> wrote:

Actually I built the code specifically to run on real time with 7fps (frames per second) on the raspberry pi. The raspberry captures the video with the camera. I tested it with pointing the camera to my PC screen ( not raspberry pi). You should be able to test it with other videos or take it to the road without adding anything.
